name: Allumer le Bot Discord 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # Relance automatique toutes les 5 heures (Automatique)

concurrency:
  group: bot-discord
  cancel-in-progress: true

jobs:
  start-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les modules
        run: npm install

      - name: Lancer le bot 🚀
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: node index.js
